import {
  ALL_PERMISSIONS,
  PERMISSIONS,
  type Permission,
} from './permission.constants.js';

export const ROLE_PERMISSIONS: Record<
  'SUPER_ADMIN' | 'HR_MANAGER' | 'DEPARTMENT_MANAGER' | 'EMPLOYEE',
  readonly Permission[]
> = {
  SUPER_ADMIN: ALL_PERMISSIONS,

  HR_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.LEAVE_VIEW_ALL,

    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_MANAGE,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_MANAGE,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_MANAGE,

    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.GOAL_READ,
    PERMISSIONS.GOAL_MANAGE,

    PERMISSIONS.RECRUITMENT_READ,
    PERMISSIONS.RECRUITMENT_MANAGE,

    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_MANAGE,

    PERMISSIONS.ANNOUNCEMENT_READ,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,

    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.AUDIT_READ,
  ],

  DEPARTMENT_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_MANAGE,

    PERMISSIONS.ATTENDANCE_READ,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.GOAL_READ,
    PERMISSIONS.GOAL_MANAGE,

    PERMISSIONS.DOCUMENT_READ,

    PERMISSIONS.ANNOUNCEMENT_READ,

    PERMISSIONS.REPORT_READ,
  ],

  EMPLOYEE: [
    PERMISSIONS.ORGANIZATION_READ,

    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.TEAM_READ,

    PERMISSIONS.ATTENDANCE_READ,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,

    PERMISSIONS.PERFORMANCE_READ,

    PERMISSIONS.GOAL_READ,
    PERMISSIONS.GOAL_MANAGE,

    PERMISSIONS.DOCUMENT_READ,

    PERMISSIONS.ANNOUNCEMENT_READ,
  ],
};